export const mockUser = {
  id: 'user_1',
  email: 'demo@devstash.io',
  name: 'John Doe',
  isPro: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-15'),
};

export const mockItemTypes = [
  {
    id: 'type_1',
    name: 'snippet',
    icon: 'Code',
    color: '#3b82f6',
    isSystem: true,
  },
  {
    id: 'type_2',
    name: 'prompt',
    icon: 'Sparkles',
    color: '#8b5cf6',
    isSystem: true,
  },
  {
    id: 'type_3',
    name: 'command',
    icon: 'Terminal',
    color: '#f97316',
    isSystem: true,
  },
  {
    id: 'type_4',
    name: 'note',
    icon: 'StickyNote',
    color: '#fde047',
    isSystem: true,
  },
  {
    id: 'type_5',
    name: 'file',
    icon: 'File',
    color: '#6b7280',
    isSystem: true,
  },
  {
    id: 'type_6',
    name: 'image',
    icon: 'Image',
    color: '#ec4899',
    isSystem: true,
  },
  {
    id: 'type_7',
    name: 'link',
    icon: 'Link',
    color: '#10b981',
    isSystem: true,
  },
];

export const mockCollections = [
  {
    id: 'coll_1',
    name: 'React Patterns',
    description: 'Common React patterns and hooks',
    isFavorite: true,
    itemCount: 12,
    itemTypeIds: ['type_1', 'type_4', 'type_7'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'coll_2',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: false,
    itemCount: 8,
    itemTypeIds: ['type_1', 'type_4'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'coll_3',
    name: 'Context Files',
    description: 'AI context files for projects',
    isFavorite: true,
    itemCount: 5,
    itemTypeIds: ['type_4', 'type_5'],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: 'coll_4',
    name: 'Interview Prep',
    description: 'Resources for interview preparation',
    isFavorite: false,
    itemCount: 34,
    itemTypeIds: ['type_4', 'type_1', 'type_7', 'type_2'],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: 'coll_5',
    name: 'Git Commands',
    description: 'Commonly used git commands',
    isFavorite: true,
    itemCount: 7,
    itemTypeIds: ['type_3', 'type_4'],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: 'coll_6',
    name: 'AI Prompts',
    description: 'Curated prompts for coding',
    isFavorite: false,
    itemCount: 6,
    itemTypeIds: ['type_2', 'type_1', 'type_4'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
];

export const mockItems = [
  {
    id: 'item_1',
    title: 'useAuth Hook',
    contentType: 'TEXT',
    content: 'const useAuth = () => {\n  // Custom auth hook implementation\n}',
    description: 'Custom authentication hook for React applications',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'auth', 'hooks'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'item_2',
    title: 'API Error Handling Pattern',
    contentType: 'TEXT',
    content: 'try {\n  // API call\n} catch (error) {\n  // Handle error\n}',
    description: 'Fetch wrapper with exponential backoff retry logic',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['api', 'error-handling'],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: 'item_3',
    title: 'Code Review Prompt',
    contentType: 'TEXT',
    content: 'Review this code for security and performance issues...',
    description: 'Prompt for AI code reviews',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    tags: ['ai', 'code-review'],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: 'item_4',
    title: 'git reset --hard HEAD~1',
    contentType: 'TEXT',
    content: 'git reset --hard HEAD~1',
    description: 'Reset to previous commit (destructive)',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['git', 'reset'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'item_5',
    title: 'useLocalStorage Hook',
    contentType: 'TEXT',
    content: 'const useLocalStorage = (key, initialValue) => { ... }',
    description: 'Persistent state management with localStorage',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'hooks', 'storage'],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: 'item_6',
    title: 'Docker Compose Up',
    contentType: 'TEXT',
    content: 'docker-compose up -d --build',
    description: 'Start containers in detached mode with rebuild',
    isFavorite: true,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['docker', 'devops'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'item_7',
    title: 'Explain Code Prompt',
    contentType: 'TEXT',
    content: 'Explain this code step by step, highlighting key concepts...',
    description: 'AI prompt for code explanations',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    tags: ['ai', 'learning'],
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    id: 'item_8',
    title: 'Meeting Notes Template',
    contentType: 'TEXT',
    content: '# Meeting Notes\n\n## Date:\n## Attendees:\n## Agenda:\n## Action Items:',
    description: 'Markdown template for meeting notes',
    isFavorite: false,
    isPinned: false,
    language: 'markdown',
    itemTypeId: 'type_4',
    tags: ['template', 'meetings'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'item_9',
    title: 'Prisma Migration Command',
    contentType: 'TEXT',
    content: 'npx prisma migrate dev --name migration_name',
    description: 'Create and apply Prisma database migration',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['prisma', 'database'],
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: 'item_10',
    title: 'React Query Setup',
    contentType: 'TEXT',
    content: 'const queryClient = new QueryClient()',
    description: 'TanStack Query client configuration',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'data-fetching'],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
  },
  {
    id: 'item_11',
    title: 'GitHub Actions Workflow',
    contentType: 'TEXT',
    content: 'name: CI\non: [push, pull_request]',
    description: 'Basic CI/CD workflow template',
    isFavorite: false,
    isPinned: false,
    language: 'yaml',
    itemTypeId: 'type_1',
    tags: ['ci-cd', 'github'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'item_12',
    title: 'Tailwind CSS Resources',
    contentType: 'URL',
    content: null,
    url: 'https://tailwindcss.com/docs',
    description: 'Official Tailwind CSS documentation',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_7',
    tags: ['css', 'docs'],
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
];

export const mockItemTypeCounts = {
  snippet: 24,
  prompt: 18,
  command: 15,
  note: 12,
  file: 5,
  image: 3,
  link: 8,
};